version: '2'
services:
    webserver:
        container_name: laravel_web
        build: ./docker/app
        restart: always
        ports:
        - '80:80'
        volumes:
        - ./:/var/www/html
        links:
        - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            -MYSQL_ROOT_PASSWORD: root
            -MYSQL_DATABASE: watch
            -MYSQL_USER: root
            -MYSQL_PASSWORD: root
        ports:
        - "3306:3306"

volumes:
    db_data:
