version: '2'
services:
    webserver:
        container_name: laravel_web
        build: ./docker/app
        restart: always
        ports:
          - "8000:80"
          - "4443:443"
        volumes:
        - ./:/var/www/html
        links:
        - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
          - MYSQL_DATABASE=watch
          - MYSQL_USER=developer
          - MYSQL_PASSWORD=developer
          - MYSQL_ROOT_PASSWORD=root
        ports:
        - "3316:3306"

volumes:
    db_data:
